language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install Flask-API
  - pip install flask-jwt-extended
  - pip install cerberus
  - pip install coveralls
  - pip install codeclimate-test-reporter
  - pip install pytest pytest-cov
  - pip install gunicorn
# command to run tests
before_script:
 - psql -c 'create database db_test;' -U postgres
script: 
  - pytest --cov=./ 
after_success:
 - coveralls
 - codeclimate-test-reporter


  
  
